version: "3"

services: 
  project_main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_main
    restart: unless-stopped
    working_dir: /app/gogoanime
    ports:
      - "3000:3000"
    networks:
      - local
    volumes:
      - /home/Documents/Github/gogoanime:/app/gogoanime
    environment:
      - NODE_ENV=development
      - PORT=3000    

      
networks:
  local:
    name: local
    driver: bridge 
    external: true    
  

      
volumes:
  project_main:
